image: registry.gitlab.com/9ide0n/terraform-modules/alpine-terraform-kitchen-tests


test_module:
  stage: "build"
  script:
    - cd services/webserver-cluster/tests
    - bundle install
    - bundle exec kitchen converge
  stage: "test"
  script:
    - bundle exec kitchen verify
    - bundle exec kitchen destroy

