image: registry.gitlab.com/9ide0n/terraform-modules/alpine-terraform-kitchen-tests

before_script:
  - cd services/webserver-cluster/tests

init:
  script:
    - bundle install
apply:
  script:
    - bundle exec kitchen converge
test:
  script:
      - bundle exec kitchen verify
destroy:
  script:
    - bundle exec kitchen destroy
