image: registry.gitlab.com/9ide0n/terraform-modules/alpine-terraform-kitchen-tests

stages:
  - converge
  - verify
  - destroy

before_script:
  - cd services/webserver-cluster/tests

kitchen_init_and_converge:
  stage: converge
  script:
    - bundle install
    - bundle exec kitchen converge
  artifacts: 
    paths:
      - tests/.kitchen/
      - tests/.terraform/
      - tests/terraform.tfstate.d/
    when: on_success
kitchen_verify:
  stage: verify
  dependencies:
    - kitchen_init_and_converge
  script:
    - bundle exec kitchen verify
kitchen_destroy:
  stage: destroy
  dependencies:
    - kitchen_init_and_converge
  when: always
  script:
    - bundle exec kitchen destroy